### ISSUE TITLE
UnauthorizedAccessException

### ISSUE THREAD

**Issue by beng81** [serras/SparkleShare#13] opened 2012-03-07 12:05 UTC
If I'm running Sparkleshare on Windows Vista, i get an UnauthorizedAccessException if SparkleShare is not running as administrator:

``` c#
Unbehandelte Ausnahme: System.UnauthorizedAccessException: Der Zugriff auf den Registrierungsschlüssel "HKEY_CLASSES_ROOT\sparkleshare" wurde verweigert.
   bei Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   bei Microsoft.Win32.RegistryKey.CreateSubKey(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistrySecurity registrySecurity)
   bei Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   bei Microsoft.Win32.Registry.SetValue(String keyName, String valueName, Object value, RegistryValueKind valueKind)
   bei SparkleShare.SparkleController.InstallProtocolHandler()
   bei SparkleShare.SparkleControllerBase.Initialize()
   bei SparkleShare.SparkleController.Initialize()
   bei SparkleShare.Program.Main(String[] args)
```

Is it possible to add a setting to the compiled SparkleShare.exe, so it always requests for  Administrator rights?

**Comment by hbons** [comment] 2012-03-12 17:09
dupe of #14

**Closed as completed** 2012-03-13 08:36 UTC
