### ISSUE TITLE
Windows documentation not clear enough

### ISSUE THREAD

**Issue by adriangibanelbtactic** [serras/SparkleShare#1] opened 2012-01-15 10:32 UTC
I have seen this line and that's not clear for any newbie that tries to build sparkleshare on its own:

  When you clone the repository, remember to run git submodule update --init.

I ask you for modifying your instructions to be similar to the wimh wiki instructions. Exact lines that I am talking about are:
"""
install msysGit PortableGit-1.7.4

```
rename the .7z file to .exe, execute and extract to C:\msysgit
```

start C:\msysgit\git-cmd.bat and execute:

md \projects
cd \projects
git clone -b windows git://github.com/wimh/SparkleShare.git
cd SparkleShare
git submodule update --init

"""

**Comment by serras** [comment] 2012-01-15 10:33
The most up-to-date documentation on how to build SparkleShare on Windows can be found in https://github.com/serras/SparkleShare/blob/gettext-cs/README.windows.md

**Comment by adriangibanelbtactic** [comment] 2012-01-15 10:36
I confirm that the bug still exists on the given url.

**Comment by serras** [comment] 2012-01-15 10:46
I rewrote that to use non-portable msysGit, which works equally as well, but has a nice installer: https://github.com/serras/SparkleShare/blob/gettext-cs/README.windows.md

**Comment by adriangibanelbtactic** [comment] 2012-01-15 11:06
My bug is not about portable msysGit versus non-portable msysGit.

The bug is about the instructions not being useful at all for someone that do not how Git works at all while the wimh instructions were.

Even more you could thing to explain it with some commands (as I have asked you) on how to create a folder, clone your repository and then run the submodule update init command.

But that would be wrong because git commands wouldn't work at all. Why's that? Because git it's not installed at all. How am I supposed to use git in the first step if you are asking me to install it as the third step.

What I mean is that the Repository clone should be the third step :).

So... Instructions for windows in my opinion should have two requisites:
- They should work in a fresh installed Windows machine
- They should not imply that the user knows how to use Git

I hope that my explanation is clear enough now :).

**Comment by serras** [comment] 2012-01-15 11:07
Ok, I see. I'll work on more detailed instructions in a few hours.
Sorry for the misunderstandings :S

**Comment by wimh** [comment] 2012-01-15 12:37
I wrote the instructions in a way that any (windows) developer should be able to execute them. I did not assume git or c# knowledge. That also means it includes more details than strictly necessary, but for those who know what they are doing, they can do it their own way. And having a well described environment, makes it easier to reproduce bugs.  

Two examples:

I said to use PortableGit, because at the moment I wrote that, the other version did not include `git-cmd.bat`. Having `git-cmd.bat` avoids me to explain how to make git properly working. 

I said to use `C:\msysgit` for git, so I just could use it in code [(*)](https://github.com/serras/SparkleShare/commit/d91220f04e8cb33878c43871059eb55a85577cf6#L7R64).

**Comment by serras** [comment] 2012-01-19 19:37
I'm currently in my exam period, so it took more time than expected, but I rewrote the build instructions to make it easier for newcomers, as both of you suggested. The new instructions are available in https://github.com/serras/SparkleShare/blob/gettext-cs/README.windows.md, what do you think?

**Comment by adriangibanelbtactic** [comment] 2012-01-19 23:43
- First line: When you clone... should be removed. 
- In the first console instructions: 

cd / 
should be changed into: 
C: 
cd c:\ 

*Well done about: 

C: 
cd c:\SparkleShare 

I almost forgot about windows changing the current path by a drive basis and not changing user current path directly. 
- Last console instructions: 

cd /c/Sparkleshare 
should be: 
C: 
cd c:\Sparkleshare 
- About getting latest changes addedum: 

I think you should say something like: 
"Build step " 
in one of the former steps and then refer to it with something like: 

and then run the build in the command shell as we did at "Build step" step. 

In the next days I will try the instructions step by step to validate them. 

----- Mensaje original -----

> De: "Alejandro Serrano"
> reply@reply.github.com
> Asunto: Re: [SparkleShare] Windows documentation not clear enough
> (#1)
> 
> I'm currently in my exam period, so it took more time than expected,
> but I rewrote the build instructions to make it easier for
> newcomers, as both of you suggested. The new instructions are
> available in
> https://github.com/serras/SparkleShare/blob/gettext-cs/README.windows.md,
> what do you think?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/serras/SparkleShare/issues/1#issuecomment-3572823

## 

Adrián Gibanel 
I.T. Manager 

+34 675 683 301 
www.btactic.com 

Ens podeu seguir a/Nos podeis seguir en: 

i 

Abans d´imprimir aquest missatge, pensa en el medi ambient. El medi ambient és cosa de tothom. / Antes de imprimir el mensaje piensa en el medio ambiente. El medio ambiente es cosa de todos. 

AVIS: 
El contingut d'aquest missatge i els seus annexos és confidencial. Si no en sou el destinatari, us fem saber que està prohibit utilitzar-lo, divulgar-lo i/o copiar-lo sense tenir l'autorització corresponent. Si heu rebut aquest missatge per error, us agrairem que ho feu saber immediatament al remitent i que procediu a destruir el missatge . 

AVISO: 
El contenido de este mensaje y de sus anexos es confidencial. Si no es el destinatario, les hacemos saber que está prohibido utilizarlo, divulgarlo y/o copiarlo sin tener la autorización correspondiente. Si han recibido este mensaje por error, les agradeceríamos que lo hagan saber inmediatamente al remitente y que procedan a destruir el mensaje .

**Comment by serras** [comment] 2012-01-20 07:25
I removed the first line and referred to instructions as "clone step", "build step" and "build installer step". This makes things much clearer now :D

About using cd /c/SparkleShare, this is the way it works in Git Bash, which is a Unix-like shell. So here we are using two different kinds of shells: for Git we use Bash, so we make `cd /c/SparkleShare` but for building we use the Windows command prompt, so we use `C: ; cd SparkleShare`

**Comment by adriangibanelbtactic** [comment] 2012-01-20 11:07
I have just tried the instructions and they seem fine to me.
I have not tested that last part about update though but I suppose it's ok.

Thank you for the updates.

**Comment by wimh** [comment] 2012-01-21 23:15
I have verified the instructions using a almost blank windows xp machine.

Basically it is ok, I have created a pull request with some improvements.

When installing msysgit, a lot of questions are asked. I added a line saying to use the default.

SmartIrc4net is no longer needed

And I think it is better to specify which Wix version to use.

Feel free to change it in a different way.

Building the msi does not work, but I will explain that in issue #2

**Comment by wimh** [comment] 2012-01-21 23:34
And by the way, I think you should rename the gettext-cs branch to windows. 

I created the gettext-cs to work in, to avoid breaking the build in the windows branch. That way I did not need to test every commit, because the instructions use the windows branch.

See also http://nvie.com/posts/a-successful-git-branching-model/ for a more complex example of branch usage.

**Comment by serras** [comment] 2012-01-22 18:52
I just used the same of the branch I started working on. Right now, in my repo I have three branches:
- `master` is a copy of `hbons/master`
- `ideas` is where I'm working on new idea for entire SparkleShare
- `gettext-cs` (that should be renamed) is where I work on the Windows port

Do you know any good place where it explains how to change the name of the branch without losing all the tracking information?

**Comment by wimh** [comment] 2012-01-23 19:44
> Do you know any good place where it explains how to change the name of the branch without losing all the tracking information?

I think I can explain what to do.

```
#delete windows branch (if it exists)
git branch -d windows
#delete windows branch on github (if it exists)
git push origin :windows

#make sure you are on the gettext-cs branch
git checkout gettext-cs
#create a new windows branch based on the current HEAD
git branch windows
#move to the (new) windows branch
git checkout windows
#upload it to github
git push origin windows:windows

#later you might want to delete the gettext-cs branch (but that can wait)
git push origin :gettext-cs
```

you don't need to worry much about git losing tracking information. git is very smart about that, as long as you have somehing point to a commit (branch, tag), you can always return to that commit, and all parent commits will keep exist. But if you worry you can create a backup copy of your repo, or create backup branches (`git branch old_branch`).

**Comment by adriangibanelbtactic** [comment] 2012-01-24 10:04
Won' t these steps make unusable the git repository for the ones that had already pulled it? 

I'm not quite sure but I think this is equivalent (on effects) to rebasing. 
Check: 
The Perils of Rebasing 
on: 
http://progit.org/book/ch3-6.html 

Alternatively you can always think that not so many developers have already pulled your git repository for working on it. 

----- Mensaje original -----

> De: "wimh"
> reply@reply.github.com
> Asunto: Re: [SparkleShare] Windows documentation not clear enough
> (#1)
> 
> > Do you know any good place where it explains how to change the name
> > of the branch without losing all the tracking information?
> 
> I think I can explain what to do.
> 
> #delete windows branch (if it exists)
> git branch -d windows
> #delete windows branch on github (if it exists)
> git push origin :windows
> 
> #make sure you are on the gettext-cs branch
> git checkout gettext-cs
> #create a new windows branch based on the current HEAD
> git branch windows
> #move to the (new) windows branch
> git checkout windows
> #upload it to github
> git push origin windows:windows
> 
> #later you might want to delete the gettext-cs branch (but that can
> wait)
> git push origin :gettext-cs
> 
> you don't need to worry much about git losing tracking information.
> git is very smart about that, as long as you have somehing point to
> a commit (branch, tag), you can always return to that commit, and
> all parent commits will keep exist. But if you worry you can create
> a backup copy of your repo, or create backup branches (`git branch
> old_branch`).

## 

Adrián Gibanel 
I.T. Manager 

+34 675 683 301 
www.btactic.com 

Ens podeu seguir a/Nos podeis seguir en: 

i 

Abans d´imprimir aquest missatge, pensa en el medi ambient. El medi ambient és cosa de tothom. / Antes de imprimir el mensaje piensa en el medio ambiente. El medio ambiente es cosa de todos. 

AVIS: 
El contingut d'aquest missatge i els seus annexos és confidencial. Si no en sou el destinatari, us fem saber que està prohibit utilitzar-lo, divulgar-lo i/o copiar-lo sense tenir l'autorització corresponent. Si heu rebut aquest missatge per error, us agrairem que ho feu saber immediatament al remitent i que procediu a destruir el missatge . 

AVISO: 
El contenido de este mensaje y de sus anexos es confidencial. Si no es el destinatario, les hacemos saber que está prohibido utilizarlo, divulgarlo y/o copiarlo sin tener la autorización correspondiente. Si han recibido este mensaje por error, les agradeceríamos que lo hagan saber inmediatamente al remitente y que procedan a destruir el mensaje .

**Comment by wimh** [comment] 2012-01-24 21:27
@adriangibanelbtactic true, users who have already a local copy of the git repo also need to change branch to keep up to date. But it is easy to explain what they need to do. It is possible to keep both the windows and gettext-cs branch up to date to give users more time to make the switch.

I'm no git expert, but afaik my description of the actions does not change the commit history, but a merge or rebase can change the commit history by moving or introducing new commits. If you just want to rename a branch, there is no need to merge, just creating a new branch is easier in my opinion.

**Comment by serras** [comment] 2012-02-29 20:23
Windows documentation has been merged into main branch, and we not longer need `gettext-cs` branch as everything is in `master`.

**Closed as completed by serras** 2012-02-29 20:23 UTC
